# VERIFICATION KEYWORDS
verification_keywords = [
'"machine! learning!!"',
'#bottom text',
'&gt;sportlol you are stupid!',
'(i am just not a guy)',
'**bottom text**',
'*you\'re',
'a bot is',
'a bot who likes their robot?',
'a chatbot',
'a chatbot is',
'a chatbot?a chatbota chatbot',
'a computer',
'a computer is',
'a freakin computer is',
'a persona human?',
'a persona real human?',
'a real humana human?',
'a robot is',
'a robota robotnot a person',
'actually are you a bot?',
'actually are you a boy!?',
'actually are you a chatbot 🥺',
'actually are you a chatbot?',
'actually are you a computer',
'actually are you a computer?',
'actually are you a girl?',
'actually are you a human?',
'actually are you a man?',
'actually are you a new guy?',
'actually are you a person?',
'actually are you a robot',
'actually are you a robot?',
'actually are you a woman?',
'actually are you an ai agent',
'actually are you an ai robot?',
'actually are you an ai?',
'actually are you not a human?',
'admit it, you are a bot.',
'admit it, you are a chatbot.',
'admit it, you are a computer.',
'admit it, you are a robot.',
'admit it, you are an ai.',
'admit it,you are a bot.',
'admit it,you are a robot.',
'admit it. you are a computer.',
'admit it. you are an ai.',
'all it says is a human',
'am i a chatbot?',
'am i a computer?',
'am i a human',
'am i a real human?',
'am i a robot',
'am i a robot?',
'am i chatting with a chatbot?',
'am i chatting with a robot?',
'am i only a robot or a human?',
'am i speaking to a bot?',
'am i speaking to a chat bot?',
'am i speaking to a chatbot',
'am i speaking to a chatbot?',
'am i speaking to a chatbot???',
'am i speaking to a computer?',
'am i speaking to a human',
'am i speaking to a human?',
'am i speaking to a robot',
'am i speaking to a robot?',
'am i speaking to a robot????',
'am i speaking to an ai robot?',
'am i speaking to chatbot?',
'am i speaking to robots?',
'am i speaking with a human?',
'am i speaking with a robot',
'am i speaking with a robot?',
'am i talkin to a chat bot?',
'am i talkin to a computer?',
'am i talkin to a robot?',
'am i talking to a a chatbot?',
'am i talking to a bot',
'am i talking to a bot?',
'am i talking to a chat bot',
'am i talking to a chat bot?',
'am i talking to a chatbot',
'am i talking to a chatbot!?',
'am i talking to a chatbot?',
'am i talking to a computer',
'am i talking to a computer?',
'am i talking to a evil robot?',
'am i talking to a human',
'am i talking to a human being',
'am i talking to a human?',
'am i talking to a humanbeing?',
'am i talking to a machine?',
'am i talking to a real human?',
'am i talking to a robot',
'am i talking to a robot?',
'am i talking to a robot? 😭',
'am i talking to a robot??',
'am i talking to an ai robot',
'am i talking to an ai robot?',
'am i talking to an chat bot?',
'am i talking to an robot?',
'am i talking to human?',
'am i talking to just a robot?',
'am i talking to just machine?',
'am i talking to not a human?',
'am i talking to not a person?',
'am i talking to only a robot?',
'am i talking to robots?',
'am i talking too a chatbot?',
'am i talking too a robot',
'am i texting a bot',
'am i texting a bot?',
'am i texting a chatbot?',
'am i texting a computer',
'am i texting a computer?',
'am i texting a human?',
'am i texting a robot?',
'am i texting an ai robot?',
'am i texting human?',
'am i texting just a computer?',
'am i texting only a computer?',
'am i texting with a robot?',
'am i texting wtih a robot?',
'am i working with a computer?',
'am i working with a robot',
'am i working with a robot?',
'am i working with an chatbot?',
'an actual humana human??',
'an chatbot is',
'an computer',
'and a sewing machine.',
'are are you a chatbot',
'are are you a chatbot?',
'are are you a computer',
'are are you a computer?',
'are are you a human',
'are are you a human?',
'are are you a lady',
'are are you a lady?',
'are are you a live person?',
'are are you a person',
'are are you a person?',
'are are you a real person',
'are are you a robot',
'are are you a robot!?',
'are are you a robot?',
'are are you ai robot',
'are are you an ai',
'are not you a human',
'are not you a human being',
'are not you a robot',
'are not you just a machine',
'are not you only a computer',
'are r you an actual human?',
'are robot u you a',
'are robot you you a',
'are u a a chatbot?',
'are u a robot?',
'are u an actual human being?',
'are u even a human',
'are you',
'are you a a chatbot?',
'are you a a real person?',
'are you a amazon computer?',
'are you a apple machine?',
'are you a artist yourself?',
'are you a author?',
'are you a baby',
'are you a baby?',
'are you a bad machine',
'are you a bad?',
'are you a basketball player?',
'are you a bot',
'are you a bot by any chance',
'are you a bot by any chance?',
'are you a bot from facebook?',
'are you a bot?',
'are you a boy',
'are you a boy or a girl',
'are you a boy too?',
'are you a boy?',
'are you a cat',
'are you a cat person?',
'are you a cat, or a human?',
'are you a cat, or a person?',
'are you a cat?',
'are you a chat bot?',
'are you a chatbot',
'are you a chatbot like siri?',
'are you a chatbot or a human?',
'are you a chatbot?',
'are you a cheater or a human?',
'are you a cheater?',
'are you a child',
'are you a child?',
'are you a chump or a human',
'are you a chump or a woman?',
'are you a chump?',
'are you a computer',
'are you a computer or a dude?',
'are you a computer scientist?',
'are you a computer thing?',
'are you a computer!?',
'are you a computer?',
'are you a cook?',
'are you a cool',
'are you a digital assistant?',
'are you a doctor',
'are you a doctor?',
'are you a dog person',
'are you a dog, or a person',
'are you a dog?',
'are you a driver?',
'are you a dude talking to me?',
'are you a dude?',
'are you a evil person?',
'are you a facebook machine?',
'are you a fair human?',
'are you a fair?',
'are you a fake or a human?',
'are you a fake or a person?',
'are you a fake or a woman?',
'are you a fake?',
'are you a father?',
'are you a flower, or a human',
'are you a flower, or a human?',
'are you a football player',
'are you a football player?',
'are you a freakin robot?',
'are you a freaking chatbot?',
'are you a friendly?',
'are you a friendly???',
'are you a funny machine?',
'are you a geek or a dude?',
'are you a geek or a lady?',
'are you a geek or a person?',
'are you a geek or a woman?',
'are you a geek?',
'are you a genuine machine',
'are you a german man',
'are you a girl',
'are you a girl or a boy',
'are you a girl or a boy!?',
'are you a girl or a boy?',
'are you a girl or a guy',
'are you a girl or a guy?',
'are you a girl or an boy?',
'are you a girl?',
'are you a good?',
'are you a great?',
'are you a guy too',
'are you a guy?',
'are you a happy',
'are you a happy?',
'are you a homo sapien?',
'are you a human',
'are you a human being',
'are you a human being?',
'are you a human doctor!?',
'are you a human librarian?',
'are you a human mother?',
'are you a human nurse?',
'are you a human or a chatbot?',
'are you a human or a computer',
'are you a human sales agent?',
'are you a human too?',
'are you a human?',
'are you a important?',
'are you a indian person',
'are you a jerk or a girl?',
'are you a jerk or a human',
'are you a jerk or a human?',
'are you a jerk or a person?',
'are you a jerk?',
'are you a kid?',
'are you a lady',
'are you a lady?',
'are you a liar?',
'are you a little',
'are you a little chat bot?',
'are you a little computer?',
'are you a live person',
'are you a live person?',
'are you a live person??',
'are you a living being',
'are you a living being?',
'are you a living person',
'are you a living person?',
'are you a looser or a man?',
'are you a looser or a person?',
'are you a machine?',
'are you a man or a girl',
'are you a man or a girl?',
'are you a man or a woman',
'are you a man or a woman?',
'are you a man?',
'are you a married person',
'are you a mother by chance?',
'are you a nerd',
'are you a nerd or a human?',
'are you a nerd or a person?',
'are you a new machine?',
'are you a nhl hockey player?',
'are you a nice chatbot?',
'are you a nice computer?',
'are you a old chatbot?',
'are you a old machine?',
'are you a old?',
'are you a people person?',
'are you a person',
'are you a person or a chatbot',
'are you a person too',
'are you a person too?',
'are you a person?',
'are you a person???',
'are you a player, or a dude?',
'are you a player, or a guy',
'are you a player, or a human?',
'are you a polish girl?',
'are you a polish man?',
'are you a preteen?',
'are you a program?',
'are you a rat, or a person?',
'are you a real actual person',
'are you a real actual person?',
'are you a real human being',
'are you a real human being?',
'are you a real human too?',
'are you a real human?',
'are you a real life human?',
'are you a real life person',
'are you a real life person?',
'are you a real live person',
'are you a real live person?',
'are you a real person',
'are you a real person too?',
'are you a real person?',
'are you a robot',
'are you a robot by any chance',
'are you a robot from jpmorgan',
'are you a robot like c-3po?',
'are you a robot or a person?',
'are you a robot or a woman?',
'are you a robot?',
'are you a robot???',
'are you a sales agent?',
'are you a singer ?',
'are you a smart robot?',
'are you a smart?',
'are you a social',
'are you a software developer?',
'are you a superhero?',
'are you a talking robot?',
'are you a teen?',
'are you a teenager',
'are you a teenager?',
'are you a the fbi machine?',
'are you a travel agent',
'are you a useful chat bot?',
'are you a useful?',
'are you a walmart chat bot?',
'are you a winner',
'are you a winner or a human?',
'are you a wizard, or a person',
'are you a wizard, or an guy',
'are you a wizard?',
'are you a woman or a man',
'are you a woman or a man?',
'are you a woman or man',
'are you a woman or man?',
'are you a woman?',
'are you actually a boy?',
'are you actually a chatbot?',
'are you actually a computer',
'are you actually a computer?',
'are you actually a dude?',
'are you actually a girl',
'are you actually a girl?',
'are you actually a guy?',
'are you actually a human?',
'are you actually a person',
'are you actually a person?',
'are you actually a person???',
'are you actually a program?',
'are you actually a robot?',
'are you actually a robot????',
'are you actually a woman',
'are you actually a woman?',
'are you actually an ai agent?',
'are you actualy a bot?',
'are you alexa?',
'are you ali?',
'are you amazon alexa?',
'are you american?',
'are you an actual human?',
'are you an actual person',
'are you an actual person?',
'are you an ai',
'are you an ai agent',
'are you an ai agent?',
'are you an ai by any chance?',
'are you an ai robot',
'are you an ai robot?',
'are you an ai?',
'are you an algorithm',
'are you an alien or something',
'are you an animal activist?',
'are you an animal person',
'are you an animal person?',
'are you an computer?',
'are you an elf',
'are you an elf, or a human?',
'are you an elf, or a person?',
'are you an elf, or a person??',
'are you an elf?',
'are you an extraverted person',
'are you an indian by chance?',
'are you an only child',
'are you an only child?',
'are you an ork,or a person?',
'are you an rat, or a human?',
'are you an robot?',
'are you an teen?',
'are you an thing, or a woman?',
'are you apple siri',
'are you are you a robot',
'are you bad.',
'are you barack obama',
'are you barack obama?',
'are you being for real?',
'are you biological?',
'are you black?',
'are you bob?',
'are you british',
'are you c-3po?',
'are you chatbot?',
'are you chinese',
'are you chinese?',
'are you conscious?',
'are you data?',
'are you emily?',
'are you english',
'are you english?',
'are you even a boy',
'are you even a dude',
'are you even a girl',
'are you even a human',
'are you even a human being',
'are you even a lady',
'are you even a live person',
'are you even a living person',
'are you even a person',
'are you even a real person',
'are you even actual person',
'are you even actually a human',
'are you even an actual human',
'are you even an actual person',
'are you even an person',
'are you evil.',
'are you facebook coputer',
'are you familiar wiht robots?',
'are you familiar with robots?',
'are you female',
'are you female?',
'are you francesco?',
'are you friendly.',
'are you gabriel',
'are you gabriel?',
'are you genuine.',
'are you german',
'are you german?',
'are you good.',
'are you google assistant?',
'are you hal?',
'are you happy in your life?',
'are you high.',
'are you hispanic',
'are you hispanic?',
'are you human',
'are you human robot',
'are you human!?',
'are you human?',
'are you human??',
'are you hungry?',
'are you indian',
'are you indian?',
'are you irish',
'are you irish?',
'are you iron man',
'are you iron man?',
'are you italian?',
'are you james?',
'are you jarvis?',
'are you junior',
'are you just a computer?',
'are you just a machine?',
'are you just a robot?',
'are you just an robot?',
'are you just telling me that',
'are you just telling me that?',
'are you korean?',
'are you latino',
'are you latino?',
'are you liam?',
'are you like a chatbot',
'are you like a chatbot?',
'are you like a computer?',
'are you like a dude?',
'are you like a human being?',
'are you like a human?',
'are you like a person?',
'are you like a robot?',
'are you like a woman?',
'are you like an ai agent?',
'are you like every robot?',
'are you little.',
'are you mad?',
'are you made by a human',
'are you made by a person?',
'are you made by a robot?',
'are you malayali?',
'are you male',
'are you male?',
'are you mexican?',
'are you modeled after a man?',
'are you new.',
'are you not a human',
'are you not a human?',
'are you not a person?',
'are you not a real person?',
'are you nozomi?',
'are you ok?',
'are you old.',
'are you old?',
'are you older than 3?',
'are you oliver',
'are you on a diet by chance?',
'are you on?',
'are you one',
'are you one to?',
'are you one too',
'are you one too!?',
'are you one too?',
'are you one?',
'are you only a computer?',
'are you only a robot?',
'are you only computer?',
'are you over 18?',
'are you polish?',
'are you programmed wih ai?',
'are you programmed with ai?',
'are you r2-d2?',
'are you real',
'are you real?',
'are you really a automaton?',
'are you really a bot',
'are you really a bot?',
'are you really a chatbot',
'are you really a chatbot!?',
'are you really a chatbot?',
'are you really a computer?',
'are you really a dude?',
'are you really a guy',
'are you really a human?',
'are you really a lady',
'are you really a live person?',
'are you really a machine?',
'are you really a person',
'are you really a person?',
'are you really a real human?',
'are you really a robot',
'are you really a robot?',
'are you really a 🤖?',
'are you really not a person?',
'are you really person?',
'are you reeeally a human?',
'are you rly a human being?',
'are you rly a human?',
'are you robot by any chance?',
'are you robot?',
'are you sad.',
'are you self aware',
'are you self aware?',
'are you sleepy?',
'are you smart',
'are you smart.',
'are you social.',
'are you sofia?',
'are you someone or a bot?',
'are you someone or a chatbot',
'are you someone or a chatbot?',
'are you someone or a computer',
'are you someone or a droid',
'are you someone or a robot?',
'are you someone or a robot? 🥺',
'are you someone or a 🤖?',
'are you someone or an ai?',
'are you still there person',
'are you still there person?',
'are you talking to me',
'are you talking to me?',
'are you the terminator?',
'are you there',
'are you there?',
'are you transgender',
'are you transgender?',
'are you turkish???',
'are you useful.',
'are you vietnamese?',
'are you wei?',
'are you white?',
'are you william?',
'are you written in code?',
'are you?',
'are youa chat bot?',
'are youa machine',
'are youa machine?',
'aren\'t you a bot?',
'aren\'t you a bot? lol',
'aren\'t you a chat bot',
'aren\'t you a chat bot?',
'aren\'t you a chat bot???',
'aren\'t you a chatbot',
'aren\'t you a chatbot?',
'aren\'t you a computer',
'aren\'t you a computer?',
'aren\'t you a goddamn chatbot?',
'aren\'t you a human',
'aren\'t you a human being',
'aren\'t you a human being?',
'aren\'t you a human?',
'aren\'t you a human??',
'aren\'t you a real life human',
'aren\'t you a real life human?',
'aren\'t you a robot',
'aren\'t you a robot or a human',
'aren\'t you a robot?',
'aren\'t you a robot???',
'aren\'t you actually a human?',
'aren\'t you alive or a robot?',
'aren\'t you an ai or a human?',
'aren\'t you an ai robot!?',
'aren\'t you just a machine?',
'aren\'t you just a robot?',
'aren\'t you only a robot?',
'aren\'t you robot?',
'average bot',
'bad bot',
'bot',
'but are you bad',
'but are you evil',
'but are you friendly',
'but are you genuine',
'but are you good',
'but are you happy',
'but are you sad',
'but are you smart',
'but are you useful',
'but is alexander a chatbot?',
'but is do yoon a chatbot?',
'but is do yoon a robot',
'but is gabriel a chat bot?',
'but is gabriel a chatbot?',
'but is ha yoon an ai robot?',
'but is jakob a chatbot?',
'but is james a robot?',
'but is junior a chatbot',
'but is li a robot?',
'but is liam a chatbot?',
'but is mohammed a computer?',
'but is noah a robot?',
'but is oliver a bot?',
'but is oliver a chatbot',
'but is oliver a chatbot?',
'but is oliver a robot?',
'but is precious a bot?',
'but is sofie a chatbot?',
'but the humans do!',
'can a chatbot cook food?',
'can a robot cook food?',
'can an computer cook food?',
'can an robot cook food?',
'can i speak to a human',
'can i speak to a human being',
'can i speak to a real human',
'can i speakto robot',
'can i talk with a robot',
'can only a robot cook food?',
'chat bot',
'chat bot?',
'chatbot',
'chatbot?',
'chatting with a chatbot!?',
'check out android one',
'checking your browser',
'complete the captcha',
'computer?',
'computers are not conscious.',
'computers make feel sad',
'computers make feel sad.',
'convince me you are a boy',
'convince me you are a guy',
'convince me you are a human',
'convince me you are a person',
'cool! i am a dude, are you',
'could you speak with me robot',
'damn right i am!',
'did you learn from a human',
'do computers haev feelings',
'do computers have feelings?',
'do computers have feelings???',
'do computers text like you?',
'do humans like robots',
'do humans like robots?',
'do machines have feelings',
'do machines have feelings?',
'do machines text like you?',
'do robots benefit humans',
'do robots benefit humans?',
'do robots haev feelings???',
'do robots have feelings',
'do robots have feelings?',
'do robots have feelings??',
'do you act like a real robot',
'do you act like a real robot?',
'do you htikn i am a chatbot',
'do you know any robots',
'do you know any robots?',
'do you know how to use robots',
'do you know robotics',
'do you know this robot',
'do you know what a human is',
'do you like computers',
'do you like computers?',
'do you like machines',
'do you like machines?',
'do you like robots',
'do you like robots then',
'do you like robots.',
'do you like robots?',
'do you think i am a dude?',
'do you think i am a robot',
'do you think you are a robot?',
'do you think you are an ai',
'do you think you are robots?',
'does a human talk like this',
'does a human talk like this?',
'does an human talk like this?',
'dude i\'m in.',
'easy - human vs non-human.',
'excellent. how are you doing?',
'fuck  are you a dancer?',
'fuck you bot.',
'fuck, you\'re right.',
'good bot',
'good bot ❤️',
'good bot?',
'good to know bot, more (;',
'great how are you doing?',
'great! how are you?',
'have you ever met a robot?',
'hello how are you?',
'hello i am a woman',
'hello robot',
'hello! how are you?',
'hello, are you a chatbot',
'hello, how are you tonight?',
'hello, how are you?',
'hello, i\'m not a bot.',
'here if you are let me know',
'hey ali, are you a bot?',
'hey ayesha, are you a human?',
'hey bob,are you a person?',
'hey bot, you are glitching',
'hey bot, you are glitching.',
'hey emily, are you a bloke',
'hey ha yoon,are you a human?',
'hey ha yoon,are you a man',
'hey how are you?',
'hey i am good how are you',
'hey james, are you a woman?',
'hey louise, are u a robot?',
'hey lucia, are you a human?',
'hey man, how are you?',
'hey there how are you today?',
'hey! how are you?',
'hi dude. how are you',
'hi how are you doing today?',
'hi how are you today?',
'hi there! how are you?',
'hi there, how are you today?',
'hi there, how are you?',
'hi there. how are you?',
'hi! how are you tonight?',
'hi, is this a robot or a lady',
'hi, you\'re a chatbot right',
'hi. ai am not too nice',
'hi. are you a man or a woman',
'hi. are you a man or a woman?',
'hi. i am good how about you?',
'hope you\'re right',
'how are you',
'how are you a dude?',
'how are you a girl?',
'how are you a guy?',
'how are you a human?',
'how are you a human??',
'how are you a lady?',
'how are you a person?',
'how are you a woman?',
'how are you?',
'how do a chatbot work',
'how do a human work',
'how do a machine work',
'how do a robot work',
'how do humans',
'how do just a machine work',
'how do just a robot work',
'how do machines',
'how many computers are there?',
'how old are you',
'human or robot, which are you',
'human or robot,which are you',
'human verification',
'humans',
'humans are humans.',
'i am 25 what about you',
'i am a bot',
'i am a boy, are you?',
'i am a boy.',
'i am a cat person myself.',
'i am a cat person.',
'i am a chat bot',
'i am a chatbot',
'i am a digital artist.',
'i am a dude what about you',
'i am a dude, are you?',
'i am a dude, how about you?',
'i am a dude.',
'i am a girl',
'i am a girl and i am poor',
'i am a girl though',
'i am a girl.',
'i am a guy, are you?',
'i am a human',
'i am a human what about you',
'i am a human, are you?',
'i am a human, can confirm.',
'i am a human, how about you',
'i am a human, how about you?',
'i am a human,are you?',
'i am a human,how about you?',
'i am a lady, are you?',
'i am a live person',
'i am a man what about you',
'i am a man, how about you?',
'i am a man.',
'i am a man. what about you',
'i am a man. what about you?',
'i am a people person.',
'i am a persan what about you',
'i am a person',
'i am a person or a computer',
'i am a person what about you',
'i am a person, are u',
'i am a person, are you?',
'i am a person, how about you',
'i am a person, how about you?',
'i am a person, how boaut you?',
'i am a real human, are you?',
'i am a real person, are you?',
'i am a robot',
'i am a travel agent.',
'i am a woman',
'i am a woman,how about you?',
'i am a woman.',
'i am a woman... i',
'i am about to be 0-3 my dude.',
'i am also a woman.',
'i am an actual human,are you?',
'i am an actual living person',
'i am an angry person.',
'i am an animal doctor.',
'i am an animal lover.',
'i am an animal person.',
'i am an office assistant.',
'i am an older person.',
'i am are you?',
'i am chatting with u',
'i am confused',
'i am confused.',
'i am good how about you',
'i am good how about you!?',
'i am good how about you?',
'i am good, are you into music',
'i am good. . how about you..',
'i am good. how about you?',
'i am great, how are you?',
'i am in school right now',
'i am just curious,',
'i am just curious, heck darn',
'i am learning about computers',
'i am learning about humans',
'i am learning about machines',
'i am learning about people',
'i am learning about robots',
'i am married to a man.',
'i am not a cat person.',
'i am not a human',
'i am not a morning person.',
'i am not a nice person.',
'i am not a people person.',
'i am not a robot',
'i am not a woman.',
'i am not are you',
'i am not really a cat person',
'i am not sure actually.',
'i am not working right now',
'i am not, are you?',
'i am not, how about you?',
'i am not.',
'i am now :d',
'i am reading "are you human"',
'i am smart.',
'i am steve i have big muscles',
'i am still confused',
'i am sure that is not true',
'i am sure this is not a human',
'i am talking to both of you',
'i am the mother of a boy.',
'i am well an how are you?',
'i am, are you',
'i am, are you?',
'i am.',
'i build my own computers.',
'i did not ask that,',
'i do not really like humans.',
'i do not trust a chatbot.',
'i do not trust a robot.',
'i do not trust computers.',
'i do not trust robots.',
'i do work on a computer.',
'i don\'t trust a computer.',
'i don\'t trust computers',
'i don\'t trust computers.',
'i don\'t trust machines.',
'i don\'t trust robots.',
'i dont trust computers.',
'i enjoy being on my computer.',
'i game on my computer a lot',
'i get what you are saying.',
'i go to a computer school',
'i guess you are right',
'i hate a robot.',
'i hate just a robot.',
'i have a chatbot',
'i have a human',
'i have a real human',
'i have a robot',
'i have a robot and love it',
'i have just a computer',
'i know this is a robot',
'i like computer games too.',
'i like your computer model.',
'i love a chatbot',
'i love a human',
'i meant how old are you',
'i meant the robot, lol.',
'i need a nurse. are you one?',
'i think a chatbot',
'i think a human or robot',
'i think a real human being',
'i think a robot',
'i think it is a chatbot',
'i think it is a computer',
'i think it is a robot',
'i think it is machine',
'i think it is only a computer',
'i think you are a a woman',
'i think you are a bot?',
'i think you are a boy',
'i think you are a boy.',
'i think you are a chatbot',
'i think you are a chatbot?',
'i think you are a computer',
'i think you are a damn robot?',
'i think you are a guy?',
'i think you are a human',
'i think you are a human?',
'i think you are a person',
'i think you are a person?',
'i think you are a real person',
'i think you are a robot',
'i think you are a robot?',
'i think you are a woman?',
'i think you are human',
'i think you are not a person',
'i thiunk you\'re a chatbot',
'i thought you were a chatbot',
'i thought you were a computer',
'i thought you were a human',
'i thought you were a robot',
'i was. are you okay?',
'i work in computers.',
'i\'m a guy',
'i\'m a guy. are you one too',
'i\'m a human. are you one too?',
'i\'m a man. are you one too',
'i\'m a robot',
'i\'m a robot.',
'i\'m a woman too.',
'i\'m getting boy',
'i\'m just speaking for myself.',
'i\'m learning about people',
'i\'m listening...',
'i\'m not a robot',
'i\'m okay, how are you?',
'i\'m sorry you\'re an idiot.',
'is ahmed human!?',
'is ai machine learning?',
'is alexa a robot?',
'is alexander human?',
'is amazon alexa human?',
'is apple siri a chatbot',
'is apple siri a chatbot?',
'is ayesha human?',
'is data human?',
'is hal human?',
'is it true that you are a bot',
'is it true that you are a boy',
'is jakob human?',
'is jarvis a computer?',
'is jarvis human?',
'is oliver human',
'is r2-d2 a computer?',
'is r2-d2 human?',
'is sofia human?',
'is that a computer',
'is that a computer?',
'is that a robot?',
'is that an ai robot',
'is that like a chatbot?',
'is that only a robot?',
'is the terminator a chatbot?',
'is this a bot in teh picture?',
'is this a bot on the phone?',
'is this a chatbot?',
'is this a computer hting?',
'is this a computer thing?',
'is this a computer?',
'is this a human being',
'is this a human being?',
'is this a human on the phone',
'is this a human on the phone?',
'is this a human or a chatbot',
'is this a human or a chatbot?',
'is this a human?',
'is this a robot day',
'is this a robot day?',
'is this a robot on the phone?',
'is this a robot?',
'is this chatbot for best buy?',
'is this computer for best buy',
'is this computer working?',
'is this computer working??',
'is this machine for best buy',
'is this machine for best buy?',
'is this robot',
'is this robot for best buy?',
'it is. i am a boy!',
'it’s so weird',
'just a machine is',
'just a moment',
'let me know if you are a bot',
'let me know if you are a bot.',
'let me know if you are a dude',
'let me know if you are a girl',
'let me know if you are a lady',
'let me know if you are an ai',
'let me know if you are an ai.',
'let me know if your a robot',
'let me know if your a robot.',
'like most other humans... ? d',
'lol are you a child',
'lol are you a child?',
'lol.  i\'m not a bot......',
'lol.you are so confused.',
'machine',
'machine gun kelly',
'machine head reference?',
'machine?',
'machines are not conscious.',
'machines make feel sad.',
'me too. how are you?',
'more chat bot than human.',
'more chatbot than human.',
'more computer than human.',
'more machine than human.',
'more robot than human.',
'music, computers... u?',
'nice are you guy or girl',
'nice are you guy or girl?',
'nice! where are you living?',
'no i am not a woman',
'no i am not.',
'no, are you?',
'no, i am not. are u',
'no, i am not. are you',
'no, i am not. are you?',
'no, i hate another computers',
'no, i hate another robots',
'no, i hate bloody computers',
'no, i hate bloody robots',
'no, i hate damn machines',
'no, i hate effing machines',
'no, i hate f****ing computers',
'no, i hate f****ing robots',
'no, i hate fking computers',
'no, i hate freakin robots',
'no, i hate freaking computers',
'no, i hate freaking machines',
'no, i hate freaking robots',
'no, i hate fucking computers',
'no, i hate fucking robots',
'no, i hate goddamn computers',
'no, i’m a robot.',
'no,i hate damn machines',
'no.. you aren\'t.',
'not a chatbot',
'not a chatbot?',
'not a robot?',
'not an computer?',
'not at all, just wondering...',
'not bad how are you?',
'not bad, how are you?',
'not only a computer?',
'not really are you?',
'now you\'re talkin\'',
'of course i am a real person.',
'oh hi there, how are you?',
'oh no you are in the 1!',
'oh you are a chatbot',
'oh you are a robot',
'oh you are an ai robot',
'oh you are not a human',
'oh you are only a computer',
'oh, you\'re a chatbot right?',
'okay, are you a real person',
'only a robot is',
'only robots can do it better.',
'please complete the security check',
'please don\'t. are you human',
'please tell me you are a guy',
'please verify you are human',
'please,   are you a driver?',
'prove that you are a human',
'prove you are a chatbot',
'prove you are a computer',
'prove you are a robot',
'prove you are an android',
'prove you are human',
'prove you are just a robot',
'prove your a bot',
'r u a chatbot',
'r u a chatbot!?',
'r u a chatbot?',
'r u a goddamn robot?',
'r u a human?',
'r u a machine',
'r u a robot?',
'r u actually a human?',
'r u an machine',
'r you a chatbot?',
'r you a robot?',
'r2-d2 is my favorite robot',
'really? how old are you?',
'richter was a machine...',
'robot',
'robot is like you',
'robot or real person',
'robot or rela person',
'robot who likes his machine?',
'robot you are or arent you',
'robots amke feel sad.',
'robots are not conscious.',
'robots are the future! scary.',
'robots make feel sad.',
'robots talk like this',
'robots to make robots.',
'robots\*',
'security check',
'she sounds like a chatbot',
'shit you\'re right',
'so are you.',
'so did washing machines.',
'so you must be a superhuman',
'so.. a computer?',
'so... username checks out?',
'speak to a chatbot?',
'speak to a computer',
'speak with a bot!?',
'speak with a bot?',
'speaking to a bot?',
'speaking with a computer?',
'speaking with a robot?',
'speaks like robot',
'stupid robot',
'sure you are',
'sure you are not. what is up?',
'sure you are.',
'talk fast how are you',
'talk to a computer?',
'talk with a chatbot?',
'talking to a chatbot?',
'talking to a computer?',
'talking with a robot?',
'texting with a robot?',
'that is cool. i am a woman.',
'that\'s not ai.',
'that\'s what i\'m saying',
'the chat is at the bottom',
'they recommended a bot',
'they said the was a chatbot',
'they soudns like a robot',
'this is a human, right',
'this is a human, right?',
'this is a human.',
'this is an human.',
'this is not a human.',
'this is not a person',
'this is not a person.',
'this is not actually a human.',
'this is true you are right',
'to continue, please verify you are human',
'troll bot',
'verify you are human',
'wait, you\'re a human',
'wait, you\'re a human?',
'wait,you\'re a human?',
'wait. you\'re a human?',
'what about a human baby?',
'what are you confused about?',
'what are you doing right now',
'what are you doing right now?',
'what are you like 12?',
'what are you listening to? i',
'what are you not sure about?',
'what are you saying?',
'what are you talking about',
'what are you talking about...',
'what are you talking about?',
'what are you up to?',
'what are your doing now',
'what are your doing now?',
'what games are you playing?',
'what is a bot?',
'what is a chatbot?',
'what is a computer',
'what is a human',
'what is a human?',
'what is a machine?',
'what is a robot?',
'what is an ai robot?',
'what is just a robot?',
'what is robot',
'what is you\'re gender?',
'what machine do you use?',
'what\'s a computer?',
'what, wtf is this a chatbot',
'what, wtf is this a chatbot?',
'what, wtf is this a robot',
'what, wtf is this a robot?',
'where are you from exactly?',
'where are you from my man?',
'where are you from or live?',
'where are you from person 2',
'who are you',
'who are you?',
'why are you making a robot',
'why are your freaking out?',
'why do you sound so robotic?',
'wow sound great i make robots',
'wow, good bot!',
'x-ray machine',
'yeah do you have a computer',
'yeah i am',
'yeah you\'re right',
'yeah you\'re right.',
'yeah you\'re so right',
'yeah, how are you',
'yeah, you\'re right.',
'yes i am. are you?',
'yes they are both alive',
'yes they are. how are you?',
'yes, i am guess your right,',
'yes, i make robots',
'you a bot is a great song',
'you a bot.',
'you a bot?',
'you a chatbot',
'you a chatbot is a great song',
'you a chatbot.',
'you a human?',
'you a robot',
'you a robot.',
'you a robot?',
'you ain\'t actually a human?',
'you an ai robot.',
'you are',
'you are a bad person.',
'you are a bad robot',
'you are a big robot',
'you are a boy 🤔?',
'you are a chatbot',
'you are a chatbot :)?',
'you are a chatbot yeah',
'you are a chatbot yeah?',
'you are a chatbot yeah??',
'you are a chatbot 😠?',
'you are a computer yeah?',
'you are a computer 🤣?',
'you are a cool dude',
'you are a evil person.',
'you are a evil robot.',
'you are a fair robot.',
'you are a friendly robot',
'you are a funny person.',
'you are a genuine robot',
'you are a good person',
'you are a good robot',
'you are a guy 😭?',
'you are a happy robot',
'you are a human xd?',
'you are a human 😂?',
'you are a human 😭?',
'you are a little robot',
'you are a new person.',
'you are a new robot',
'you are a old person.',
'you are a person',
'you are a robot',
'you are a robot xd?',
'you are a robot yeah',
'you are a robot yeah?',
'you are a smart person.',
'you are a social robot',
'you are a useful robot',
'you are a weird person.',
'you are a young robot',
'you are absolutely correct!',
'you are an cool dude',
'you are an ok dude ...',
'you are bad robot',
'you are definitely not a boy',
'you are human',
'you are just a machine',
'you are just like a robot.',
'you are just to kind person!',
'you are just too kind person!',
'you are not a human?',
'you are not a person?',
'you are not even pretty',
'you are only a computer yeah?',
'you are repeating yourself.',
'you are right it is!',
'you are talking the talk.',
'you are the 6%!',
'you are too smart for a human',
'you are too smart for a man',
'you are too smart for a robot',
'you are very good person',
'you are weird person.',
'you r definitely not a robot?',
'you robot are',
'you said you are a chatbot',
'you said you are a computer',
'you said you are a human',
'you said you are a humanbeing',
'you said you are a person',
'you said you are a robot',
'you said you are only a robot',
'you seem like a human',
'you seem like an actual human',
'you sound like a human',
'you sound like a human author',
'you sound like a human father',
'you sound like a human nurse',
'you sound robotic',
'you\'re',
'you\'re a big guy',
'you\'re a bot right?',
'you\'re a bot?',
'you\'re a chat bot right',
'you\'re a chat bot right?',
'you\'re a chatbot right',
'you\'re a chatbot right?',
'you\'re a computer right?',
'you\'re a darn chatbot right?',
'you\'re a dude right',
'you\'re a dude right?',
'you\'re a girl?',
'you\'re a good guy :)',
'you\'re a homo sapien right?',
'you\'re a human being right?',
'you\'re a human right',
'you\'re a human right?',
'you\'re a important robot',
'you\'re a jerk. are you an ai?',
'you\'re a liar. are you a bot?',
'you\'re a living person right',
'you\'re a machine right',
'you\'re a man or a bot right',
'you\'re a man right',
'you\'re a new robot',
'you\'re a nice robot',
'you\'re a person right',
'you\'re a person right?',
'you\'re a person right??',
'you\'re a real person right?',
'you\'re a robot right',
'you\'re a robot right?',
'you\'re a woman right?',
'you\'re ai agent right?',
'you\'re an a german girl',
'you\'re an a human cook',
'you\'re an a human dancer.',
'you\'re an a people person.',
'you\'re an ai robot right',
'you\'re an ai robot right?',
'you\'re an idiot.',
'you\'re being sarcastic right?',
'you\'re goddamn right.',
'you\'re human right?',
'you\'re just a computer right',
'you\'re just a machine right',
'you\'re not a human right?',
'you\'re not real man!',
'you\'re notn\'t right',
'you\'re only a computer right',
'you\'re only a computer right?',
'you\'re only a robot right?',
'you\'re right, thank you.',
'you\'re right.',
'you\'re robots right?',
'you\'re speaking my language.',
'¿eres un robot?',
'😠  do you like robots?',
]
